-- CREATE TABLE IF NOT EXISTS STUDENT(
-- ROLLNO TEXT PRIMARY KEY, 
-- NAME TEXT NOT NULL,
-- ADRESS TEXT,
-- PHONE TEXT,
-- AGE INTEGER
-- );
-- INSERT INTO STUDENT(ROLLNO,NAME,ADRESS,PHONE, AGE) VALUES
-- ("1","ZAWATA","DHAKA","123",16),
-- ("2","ABDULLAH","CHATTOGRAM","321",17),
-- ("3","JUNAID","DHAKA","241",19),
-- ("4","ZAREEN","FENI","987",16),
-- ("5","FAIRUZ","KHULNA","654",20);
-- SELECT * FROM STUDENT
-- SELECT * FROM STUDENT WHERE AGE=19 AND ADRESS="DHAKA"
-- SELECT * FROM STUDENT WHERE NAME="ZAREEN" AND ADRESS="FENI"
SELECT * FROM STUDENT WHERE NAME="ZAWATA" OR ROLLNO="5"







